### ISSUE TITLE
XeLaTeX和Bibtex的命令组合

### ISSUE THREAD

**Issue by nevertiree** [ufo5260987423/BjfuLatexTemplate#4]
本模板在TexMaker中的快速构建方法为：**“XeLaTeX + 查看PDF”**，然而使用bibtex需要的快捷构建方式是**“PdfLaTeX + Bibtex + 两次PdfLatex + 查看Pdf”**

于是我几乎写一个自定义的快速构建命令

目前的暂时写为：

xelatex -interaction=nonstopmode %.tex|
bibtex %.aux|
xelatex -interaction=nonstopmode %.tex|
xelatex -interaction=nonstopmode %.tex|
dviout %.dvi

不过效果并不好，请测试。谢谢

**Comment by ufo5260987423** [comment]
这种东西不具有普适性
因为bib文件一般不会反复更改，如果出现反复更改，为何不先完成内容再调整格式？

在texmaker里面当然可以这样，在其他的编辑器中呢？
说到底，还是需要掌握处理latex文档的几个命令。

**Comment by nevertiree** [comment]
快速构建命令脚本是夸编辑器公用的
